apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-volume
  namespace: telemetry
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/loki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-volume-claim
  namespace: telemetry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
