apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: telemetry
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.4.0 # imagem para produção
          ports:
            - containerPort: 16686 # Porta da UI
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          # restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: telemetry
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
  type: ClusterIP
