apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: telemetry
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-service.telemetry.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: insurance-hub-job
        static_configs:
          - targets:
              - localhost
            labels:
              job: app-dev-logs
              __path__: /var/log/app-dev-logs.log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: telemetry
  labels:
    app: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:latest
          env:
            - name: TZ
              value: America/Sao_Paulo
          volumeMounts:
            # - name: log-volume
            #   mountPath: /var/log/app-dev-logs.log
            #   subPath: app-dev-logs.log
            # - name: promtail-config
            #   mountPath: /etc/promtail/promtail-config.yaml
            #   subPath: promtail-config.yaml
            - name: log-volume
              mountPath: /var/log
            - name: promtail-config
              mountPath: /etc/promtail-config/promtail-config.yaml
              subPath: promtail-config.yaml
          command:
            [
              "/usr/bin/promtail",
              "-config.file=/etc/promtail-config/promtail-config.yaml",
            ]
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: log-volume
          hostPath:
            path: /var/log
            type: Directory
        - name: promtail-config
          configMap:
            name: promtail-config
---
apiVersion: v1
kind: Service
metadata:
  name: promtail-service
  namespace: telemetry
  labels:
    app: promtail
spec:
  selector:
    app: promtail
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
  type: ClusterIP
